PhoneStore/Models/ViewModel/Cart/AdminInvoiceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneStore.Models.ViewModel.Cart
{
    public class AdminInvoiceModel
    {
        public int InvId { get; set; }
        public DateTime? InvDate { get; set; }
        public int? EmId { get; set; }
        public int? CusId { get; set; }
        public string InvCusName { get; set; }
        public string InvCusEmail { get; set; }
        public string InvCusPhone { get; set; }

        public string InvAddress { get; set; }
        public string InvNote { get; set; }
        public bool? InvStatus { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? ProductCount { get; set; }
        public double? Total { get; set; }
    }
}

PhoneStore/Models/ViewModel/Cart/CartItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneStore.Models.ViewModel
{
    public class CartItemViewModel
    {
        public int ProId { get; set; }
        public string ProName { get; set; }
        public string ProImage { get; set; }
        public string varImage { get; set; }
        public int qty { get; set; }
        public double? ProRetailPrice { get; set; }
        public double? ProSalePrice { get; set; }
        public string ProDescription { get; set; }
        public IEnumerable<VariantViewModel> VariantList { get; set; } 
    }
}

PhoneStore/Models/ViewModel/Cart/CartPriceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneStore.Models.ViewModel
{
    public class CartPriceViewModel
    {
        public double temp { get; set; }
        public double discount { get; set; }
        public double total { get; set; }
    }
}

PhoneStore/Models/ViewModel/Cart/CartViewModel.cs
using PhoneStore.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneStore.Models.ViewModel
{
    public class CartViewModel
    {
        public IEnumerable<CartItemViewModel> cartItem { get; set; }
        public CartPriceViewModel cartPrice { get; set; }
        public IEnumerable<AddressCity> cities { get; set; }
        public IEnumerable<AddressDistrict> district { get; set; }
        public IEnumerable<AddressWard> ward { get; set; }
        public Account Account { get; set; }
    }
}

PhoneStore/Models/ViewModel/Cart/VariantViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneStore.Models.ViewModel
{
    public class VariantViewModel
    {
        public int VarId { get; set; }
        public string VarColor { get; set; }
        public string VarColorIcon { get; set; }

        public bool Selected { get; set; }
    
    }  
}

PhoneStore/ViewComponents/NavBarViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using PhoneStore.Data;
using PhoneStore.Interfaces.Services;
using PhoneStore.Models.ViewModel;
using PhoneStore.Models.ViewModel.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PhoneStore.ViewComponents
{
    public class NavBarViewComponent : ViewComponent
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _hosting;
        private readonly IUserService _userService;
        private readonly ICartService _cartService;

        public NavBarViewComponent(IProductService productService,
            IUserService userService,
            ICartService cartService, 
            IMapper mapper, 
            IWebHostEnvironment hosting)
        {
            _productService = productService;
            _mapper = mapper;
            _hosting = hosting;
            _userService = userService;
            _cartService = cartService;
        }
        public IViewComponentResult Invoke()
        {
            var user = User as ClaimsPrincipal;
            string userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                
                HeaderViewModel model = _productService.GetMenu();
                
                model.cartCount = _cartService.CartProductCount();
                return View(model);
            }
            else
            {
                
                
                Account userModel = _userService.GetUser(Int32.Parse(userId));
                HeaderViewModel model = _productService.GetMenu();
                model.user = userModel;
                model.cartCount = _cartService.CartProductCount();
                return View(model);
            }

        }
    }
}

PhoneStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sublime</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sublime project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/styles/bootstrap4/bootstrap.min.css">

    <link href="~/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/animate.css">

    @RenderSection("css",required:false)
</head>
<body>

    <div class="super_container">

        <!-- Header -->
        <!-- Home -->
        @await Component.InvokeAsync("NavBar")
        @RenderBody()
        <!-- Footer -->

        <div class="footer_overlay"></div>
        <footer class="footer">
            <div class="footer_background" style="background-image:url(@Url.Content("~/images/footer.jpg"))"></div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="footer_content d-flex flex-lg-row flex-column align-items-center justify-content-lg-start justify-content-center">
                            <div class="footer_logo"><a href="#">Sublime.</a></div>
                            <div class="copyright ml-auto mr-auto">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </div>
                            <div class="footer_social ml-lg-auto">
                                <ul>
                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/styles/bootstrap4/popper.js"></script>
    <script src="~/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="~/plugins/greensock/TweenMax.min.js"></script>
    <script src="~/plugins/greensock/TimelineMax.min.js"></script>
    <script src="~/plugins/scrollmagic/ScrollMagic.min.js"></script>
    <script src="~/plugins/greensock/animation.gsap.min.js"></script>
    <script src="~/plugins/greensock/ScrollToPlugin.min.js"></script>
    <script src="~/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="~/plugins/Isotope/isotope.pkgd.min.js"></script>
    <script src="~/plugins/easing/easing.js"></script>
    <script src="~/plugins/parallax-js-master/parallax.min.js"></script>

    <script src="~/plugins/numeral/numeral.min.js"></script>
    <script src="~/js/search.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>